version: '3.3'
services: 

  mysql:
    image: mysql:latest
    container_name: mysqldb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: food_trends
    volumes:
      - ./db-data:/var/lib/mysql
      - ./entrypoint:/docker-entrypoint-initdb.d/
    ports:
      - "3307:3306"
    command: mysqld --init-file="/docker-entrypoint-initdb.d/food_trends.sql"

  apiBackend:
    container_name: apiBackend
    working_dir: /app
    image: 'node:12.6-slim'
    command: bash -c "yarn install && yarn dev:server"
    restart: unless-stopped
    ports: 
      - 3333:3333
    volumes: 
      - ./backend:/app

  appFrontend:
    container_name: appFrontendDist
    image: 'node:12.6-slim'
    working_dir: /app
    container_name: appFrontend
    command: bash -c "yarn install && yarn serve"
    ports: 
      - "8088:8080"
    volumes: 
      - ./frontend:/app
    restart: always


